# Generated by Django 4.0 on 2022-07-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0002_appuser_address_appuser_major_health_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='health_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.healthstatus'),
        ),
        migrations.AlterField(
            model_name='healthstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccapp.appuser'),
        ),
    ]
